# Reservoir Simulation configuration.
path: "/home/hygorcosta/Documentos/Phd/SAO/PyMEX/reservoir_tpl"
template: 'Egg_unif_ari_3_34.tpl'
prices: [126, 19, 6, 0]
nb_cycles: 2
nb_prod: 4
nb_inj: 8
time_concession: 3600
max_rate_prod: 120
max_rate_inj: 79.5
max_plat_prod: 400
max_plat_inj: 440
type_opera: 1
type_time: 0
