# Reservoir Simulation configuration.
path: "/home/hygorcosta/Documentos/Phd/PyMEX/reservoir_tpl"
template: 'NewEgg_Model_2cc.tpl'
prices: [126, 19, 6, 0]
nb_cycles: 2
nb_prod: 4
nb_inj: 8
time_concession: 3600
max_rate_prod: 30
max_rate_inj: 44
max_plat_prod: 400
max_plat_inj: 440
type_opera: 1
type_time: 0
